# Shared platform and executable output selection; no GPIO library dependencies.
set(BASE_GPIO_PLATFORM "AUTO" CACHE STRING "GPIO platform: AUTO, RPI4, RPI5, RPI CM4, RPI CM5, DESKTOP")
set_property(CACHE BASE_GPIO_PLATFORM PROPERTY STRINGS AUTO RPI4 RPI5 "RPI CM4" "RPI CM5" DESKTOP)
set(SYSTEM "${BASE_GPIO_PLATFORM}")
if(SYSTEM STREQUAL "AUTO")
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|aarch64|ARM64)")
        if(CMAKE_CROSSCOMPILING OR NOT EXISTS "/proc/device-tree/model")
            message(FATAL_ERROR "[platform.cmake()] ERROR: Set BASE_GPIO_PLATFORM to RPI4, RPI5, RPI CM4 or RPI CM5 for this ARM build")
        endif()
        file(READ "/proc/device-tree/model" GPIO_BOARD_MODEL)
        if(GPIO_BOARD_MODEL MATCHES "Raspberry Pi Compute Module 5([^0-9]|$)")
            set(SYSTEM "RPI CM5")
        elseif(GPIO_BOARD_MODEL MATCHES "Raspberry Pi Compute Module 4([^0-9]|$)")
            set(SYSTEM "RPI CM4")
        elseif(GPIO_BOARD_MODEL MATCHES "Raspberry Pi 5")
            set(SYSTEM "RPI5")
        elseif(GPIO_BOARD_MODEL MATCHES "Raspberry Pi 4")
            set(SYSTEM "RPI4")
        else()
            message(FATAL_ERROR "[platform.cmake()] ERROR: Unsupported board; select BASE_GPIO_PLATFORM explicitly")
        endif()
    else()
        set(SYSTEM "DESKTOP")
    endif()
endif()


# Compute Modules use the GPIO implementation of the corresponding Pi generation.
set(GPIO_BOARD_PLATFORM "${SYSTEM}")
if(SYSTEM STREQUAL "RPI CM4")
    set(SYSTEM "RPI4")
elseif(SYSTEM STREQUAL "RPI CM5")
    set(SYSTEM "RPI5")
endif()

if(SYSTEM STREQUAL "RPI4" OR SYSTEM STREQUAL "RPI5")
    set(BIN_BASE_DIR "/")
elseif(SYSTEM STREQUAL "DESKTOP")
    set(BIN_BASE_DIR "${CMAKE_SOURCE_DIR}")
else()
    message(FATAL_ERROR "[platform.cmake()] ERROR: Unknown BASE_GPIO_PLATFORM: ${SYSTEM}")
endif()
